export const movies = [
    {
        id: 1001,
        title: 'Inception',
        year: '2010',
        rating: 8.8,
        duration: '2h 28m',
        genres: ['Action', 'Sci-Fi', 'Adventure'],
        description: 'A thief who steals corporate secrets through dream-sharing technology is tasked with planting an idea into a CEO\'s mind. This mind-bending mission challenges reality and the limits of imagination. ',
        imageUrl: 'https://filmartgallery.com/cdn/shop/files/Inception-Vintage-Movie-Poster-Original.jpg?v=1738912645',
        director: 'Christopher Nolan',
        cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
        boxOffice: '$836.8 million',
        awards: '4 Academy Awards',
        language: 'English',
        country: 'USA',
    },
    {
        id: 1002,
        title: 'Interstellar',
        year: '2014',
        rating: 8.6,
        duration: '2h 49m',
        genres: ['Drama', 'Sci-Fi', 'Adventure'],
        description: 'A team of explorers travel through a wormhole in space to ensure humanity\'s survival, facing the unknown and the limits of love and sacrifice.',
        imageUrl: "https://images-cdn.ubuy.co.in/6352289f38bb253c44612d53-interstellar-movie-poster-24-x-36-inches.jpg",
        director: 'Christopher Nolan',
        cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
        boxOffice: '$677.5 million',
        awards: '1 Academy Award',
        language: 'English',
        country: 'USA',
    },
    {
        id: 1003,
        title: 'The Dark Knight',
        year: '2008',
        rating: 9.0,
        duration: '2h 32m',
        genres: ['Action', 'Crime', 'Drama'],
        description: 'Batman faces his greatest psychological and physical tests when the Joker unleashes chaos on Gotham City, forcing the hero to confront his own limits.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg',
        director: 'Christopher Nolan',
        cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
        boxOffice: '$1.005 billion',
        awards: '2 Academy Awards',
        language: 'English',
        country: 'USA',
    },
    {
        id: 1004,
        title: 'Forrest Gump',
        year: '1994',
        rating: 8.8,
        duration: '2h 22m',
        genres: ['Drama', 'Romance'],
        description: 'The story of Forrest Gump, a man with a low IQ, who inadvertently influences several historical events in the 20th century United States through his simple kindness and determination.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg',
        director: 'Robert Zemeckis',
        cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
        boxOffice: '$678.2 million',
        awards: '6 Academy Awards',
        language: 'English',
        country: 'USA',
    },
    {
        id: 1005,
        title: 'The Shawshank Redemption',
        year: '1994',
        rating: 9.3,
        duration: '2h 22m',
        genres: ['Drama'],
        description: 'Wrongly accused of murder, Andy Dufresne forms an unlikely friendship with Red and finds hope and redemption within the walls of Shawshank prison.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
        director: 'Frank Darabont',
        cast: ['Tim Robbins', 'Morgan Freeman', 'William Sadler'],
        boxOffice: '$73.3 million',
        awards: 'Nominated for 7 Academy Awards',
        language: 'English',
        country: 'USA',
    },
    {
        id: 1006,
        title: 'Pulp Fiction',
        year: '1994',
        rating: 8.9,
        duration: '2h 34m',
        genres: ['Crime', 'Drama'],
        description: 'A series of interconnected stories involving hitmen, a boxer, and a gangster\'s wife unfold in Quentin Tarantino\'s stylish and darkly comedic crime masterpiece.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg',
        director: 'Quentin Tarantino',
        cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
        boxOffice: '$213.9 million',
        awards: '1 Academy Award',
        language: 'English',
        country: 'USA',
    },
    {
        id: 1007,
        title: 'The Godfather',
        year: '1972',
        rating: 9.2,
        duration: '2h 55m',
        genres: ['Crime', 'Drama'],
        description: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son in this epic tale of family and power.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
        director: 'Francis Ford Coppola',
        cast: ['Marlon Brando', 'Al Pacino', 'James Caan'],
        boxOffice: '$250 million',
        awards: '3 Academy Awards',
        language: 'English',
        country: 'USA',
    },
    {
        id: 1008,
        title: 'The Matrix',
        year: '1999',
        rating: 8.7,
        duration: '2h 16m',
        genres: ['Action', 'Sci-Fi'],
        description: 'A computer hacker learns about the true nature of his reality and his role in the war against its controllers in this groundbreaking sci-fi action film.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_.jpg',
        director: 'Lana Wachowski, Lilly Wachowski',
        cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
        boxOffice: '$466.6 million',
        awards: '4 Academy Awards',
        language: 'English',
        country: 'USA',
    },
    {
        id: 1009,
        title: 'Fight Club',
        year: '1999',
        rating: 8.8,
        duration: '2h 19m',
        genres: ['Drama'],
        description: 'An insomniac office worker and a soap maker form an underground fight club that evolves into something much more in this cult classic.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_.jpg',
        director: 'David Fincher',
        cast: ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'],
        boxOffice: '$101.2 million',
        awards: 'Nominated for 1 Academy Award',
        language: 'English',
        country: 'USA',
    },
    {
        id: 1010,
        title: 'The Lord of the Rings: The Fellowship of the Ring',
        year: '2001',
        rating: 8.8,
        duration: '2h 58m',
        genres: ['Adventure', 'Drama', 'Fantasy'],
        description: 'A meek Hobbit and his companions set out on a perilous journey to destroy a powerful ring and save Middle-earth from darkness.',
        imageUrl: 'https://m.media-amazon.com/images/I/71lKy8RoFUL._UF1000,1000_QL80_.jpg',
        director: 'Peter Jackson',
        cast: ['Elijah Wood', 'Ian McKellen', 'Orlando Bloom'],
        boxOffice: '$898.2 million',
        awards: '4 Academy Awards',
        language: 'English',
        country: 'New Zealand, USA',
    },
    {
        id: 1011,
        title: 'Gladiator',
        year: '2000',
        rating: 8.5,
        duration: '2h 35m',
        genres: ['Action', 'Adventure', 'Drama'],
        description: 'A betrayed Roman general seeks vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
        imageUrl: 'https://miro.medium.com/v2/resize:fit:1400/0*TxZdqJf0MQ2mdL9p.jpg',
        director: 'Ridley Scott',
        cast: ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen'],
        boxOffice: '$503.2 million',
        awards: '5 Academy Awards',
        language: 'English',
        country: 'USA, UK',
    },
    {
        id: 1012,
        title: 'The Lion King',
        year: '1994',
        rating: 8.5,
        duration: '1h 28m',
        genres: ['Animation', 'Adventure', 'Drama'],
        description: 'A young lion prince flees his kingdom after the death of his father, only to learn the true meaning of responsibility and bravery.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9d/Disney_The_Lion_King_2019.jpg',
        director: 'Roger Allers, Rob Minkoff',
        cast: ['Matthew Broderick', 'Jeremy Irons', 'James Earl Jones'],
        boxOffice: '$968.5 million',
        awards: '2 Academy Awards',
        language: 'English',
        country: 'USA',
    },
    {
        id: 1013,
        title: 'Jurassic Park',
        year: '1993',
        rating: 8.2,
        duration: '2h 7m',
        genres: ['Adventure', 'Sci-Fi', 'Thriller'],
        description: 'A theme park showcasing genetically engineered dinosaurs turns into a nightmare when the creatures escape and terrorize the visitors.',
        imageUrl: 'https://m.media-amazon.com/images/I/917hANc0Q9L._UF1000,1000_QL80_.jpg',
        director: 'Steven Spielberg',
        cast: ['Sam Neill', 'Laura Dern', 'Jeff Goldblum'],
        boxOffice: '$1.046 billion',
        awards: '3 Academy Awards',
        language: 'English',
        country: 'USA',
    },
    {
        id: 1014,
        title: 'Titanic',
        year: '1997',
        rating: 7.9,
        duration: '3h 15m',
        genres: ['Drama', 'Romance'],
        description: 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the ill-fated R.M.S. Titanic.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BYzYyN2FiZmUtYWYzMy00MzViLWJkZTMtOGY1ZjgzNWMwN2YxXkEyXkFqcGc@._V1_.jpg',
        director: 'James Cameron',
        cast: ['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane'],
        boxOffice: '$2.264 billion',
        awards: '11 Academy Awards',
        language: 'English',
        country: 'USA',
    },
    {
        id: 1015,
        title: 'The Avengers',
        year: '2012',
        rating: 8.0,
        duration: '2h 23m',
        genres: ['Action', 'Adventure', 'Sci-Fi'],
        description: 'Earth\'s mightiest heroes must come together to stop Loki and his alien army from enslaving humanity.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8a/The_Avengers_%282012_film%29_poster.jpg',
        director: 'Joss Whedon',
        cast: ['Robert Downey Jr.', 'Chris Evans', 'Scarlett Johansson'],
        boxOffice: '$1.519 billion',
        awards: 'Nominated for 1 Academy Award',
        language: 'English',
        country: 'USA',
    },
    {
        id: 1016,
        title: 'Avatar',
        year: '2009',
        rating: 7.8,
        duration: '2h 42m',
        genres: ['Action', 'Adventure', 'Fantasy'],
        description: 'A paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BNmQxNjZlZTctMWJiMC00NGMxLWJjNTctNTFiNjA1Njk3ZDQ5XkEyXkFqcGc@._V1_.jpg',
        director: 'James Cameron',
        cast: ['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver'],
        boxOffice: '$2.923 billion',
        awards: '3 Academy Awards',
        language: 'English',
        country: 'USA',
    },
    {
        id: 1017,
        title: 'The Silence of the Lambs',
        year: '1991',
        rating: 8.6,
        duration: '1h 58m',
        genres: ['Crime', 'Drama', 'Thriller'],
        description: 'A young FBI cadet must confide in an incarcerated and manipulative killer to catch another serial killer who skins his victims.',
        imageUrl: 'https://s3.amazonaws.com/criterion-production/films/46014912ca0c20592c472f5bbe33e4f8/L9AQ95Y7z2vOIUf1ntwvpZsZx3kp8B_large.jpg',
        director: 'Jonathan Demme',
        cast: ['Jodie Foster', 'Anthony Hopkins', 'Scott Glenn'],
        boxOffice: '$272.7 million',
        awards: '5 Academy Awards',
        language: 'English',
        country: 'USA',
    },
    {
        id: 1018,
        title: 'Saving Private Ryan',
        year: '1998',
        rating: 8.6,
        duration: '2h 49m',
        genres: ['Drama', 'War'],
        description: 'During World War II, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.',
        imageUrl: 'https://m.media-amazon.com/images/M/MV5BZGZhZGQ1ZWUtZTZjYS00MDJhLWFkYjctN2ZlYjE5NWYwZDM2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
        director: 'Steven Spielberg',
        cast: ['Tom Hanks', 'Matt Damon', 'Tom Sizemore'],
        boxOffice: '$482.3 million',
        awards: '5 Academy Awards',
        language: 'English',
        country: 'USA',
    },
    {
        id: 1019,
        title: 'The Prestige',
        year: '2006',
        rating: 8.5,
        duration: '2h 10m',
        genres: ['Drama', 'Mystery', 'Sci-Fi'],
        description: 'Two rival magicians engage in a bitter competition to create the ultimate stage illusion, pushing the boundaries of science and obsession.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/Prestige_poster.jpg/250px-Prestige_poster.jpg',
        director: 'Christopher Nolan',
        cast: ['Hugh Jackman', 'Christian Bale', 'Scarlett Johansson'],
        boxOffice: '$109.7 million',
        awards: 'Nominated for 2 Academy Awards',
        language: 'English',
        country: 'USA, UK',
    },
    {
        id: 1020,
        title: 'Whiplash',
        year: '2014',
        rating: 8.5,
        duration: '1h 46m',
        genres: ['Drama', 'Music'],
        description: 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.',
        imageUrl: 'https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10488558_p_v12_ai.jpg',
        director: 'Damien Chazelle',
        cast: ['Miles Teller', 'J.K. Simmons', 'Paul Reiser'],
        boxOffice: '$49 million',
        awards: '3 Academy Awards',
        language: 'English',
        country: 'USA',
    },
    // ...existing code...
    {
        id: 1021,
        title: '3 Idiots',
        year: '2009',
        rating: 8.4,
        duration: '2h 50m',
        genres: ['Comedy', 'Drama'],
        description: 'Two friends embark on a quest to find a lost buddy. On this journey, they encounter memories of their college days and the lessons they learned from their free-spirited friend.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/d/df/3_idiots_poster.jpg',
        director: 'Rajkumar Hirani',
        cast: ['Aamir Khan', 'R. Madhavan', 'Sharman Joshi'],
        boxOffice: '₹460 crore ($90 million)',
        awards: '6 Filmfare Awards',
        language: 'Hindi',
        country: 'India',
    },
    {
        id: 1022,
        title: 'Dangal',
        year: '2016',
        rating: 8.3,
        duration: '2h 41m',
        genres: ['Biography', 'Drama', 'Sport'],
        description: 'Former wrestler Mahavir Singh Phogat trains his daughters Geeta and Babita to become India\'s world-class wrestlers, breaking stereotypes and inspiring a nation.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/9/99/Dangal_Poster.jpg',
        director: 'Nitesh Tiwari',
        cast: ['Aamir Khan', 'Fatima Sana Shaikh', 'Sanya Malhotra'],
        boxOffice: '₹2,024 crore ($311 million)',
        awards: '4 Filmfare Awards',
        language: 'Hindi',
        country: 'India',
    },
    {
        id: 1023,
        title: 'Gully Boy',
        year: '2019',
        rating: 8.0,
        duration: '2h 34m',
        genres: ['Drama', 'Music'],
        description: 'A coming-of-age story about an aspiring street rapper from the slums of Mumbai who rises against the odds to achieve his dreams.',
        imageUrl: 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTpxuHbd0Q2q56g5aVU-kB4GPYcL0b-5xgY6n0XyFhurQ9pusxt5M_8epJwOxrb4n3WGM62',
        director: 'Zoya Akhtar',
        cast: ['Ranveer Singh', 'Alia Bhatt', 'Siddhant Chaturvedi'],
        boxOffice: '₹238 crore ($34 million)',
        awards: '13 Filmfare Awards',
        language: 'Hindi',
        country: 'India',
    },
    {
        id: 1024,
        title: 'Lagaan: Once Upon a Time in India',
        year: '2001',
        rating: 8.1,
        duration: '3h 44m',
        genres: ['Adventure', 'Drama', 'Musical'],
        description: 'In colonial India, villagers challenge British officers to a game of cricket to avoid paying oppressive taxes, uniting the community in hope and resistance.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b6/Lagaan.jpg',
        director: 'Ashutosh Gowariker',
        cast: ['Aamir Khan', 'Gracy Singh', 'Rachel Shelley'],
        boxOffice: '₹65 crore ($17 million)',
        awards: '8 National Film Awards, Nominated for 1 Academy Award',
        language: 'Hindi',
        country: 'India',
    },
];